# Generated by Django 2.1.1 on 2018-09-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180905_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jim',
            new_name='Choice',
        ),
    ]
