# Generated by Django 2.1.1 on 2018-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='book',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
