# Generated by Django 2.1.1 on 2018-09-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Language of book', to='catalog.Language'),
        ),
    ]
