# Generated by Django 2.1.1 on 2018-10-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180925_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_crud_author', 'Can create, update and delete Author objects'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_crud_book', 'Can create, update and delete Book objects'),)},
        ),
    ]
